### ISSUE TITLE
Location 'United States' is giving an error in Linkedin

### ISSUE THREAD

**Issue by Alexm1988** [joaosilvalopes/linkedin-easy-apply-bot#62]
This is a part of my config.ts file:
```
// JOB SEARCH PARAMETERS
  KEYWORDS: "(sdet|QA Engineer|Software QA|Software Quality|Senior SDET).* (engineer|analyst)"
,
  LOCATION: "United States",
  WORKPLACE: {
    REMOTE: true,
    ON_SITE: false,
    HYBRID: true,
  },
  JOB_TITLE: "(sdet|QA Engineer|Software QA|Software Quality|Senior SDET).* (engineer|analyst)",
  JOB_DESCRIPTION: "^((?!(primeit))(.|[\n\r]))*$",
  JOB_DESCRIPTION_LANGUAGES: ["any"], // replace value with ["any"] to accept all job description laguages
```
With this setup, the location field is not being populated properly(it adds the space after the string in config.LOCATION) and gives error:
<img width="828" alt="Screen Shot 2023-04-26 at 10 33 56 PM" src="https://user-images.githubusercontent.com/47483121/234745642-af54702f-f2bc-4c3f-bd29-da8c12269595.png">

**Comment by Alexm1988** [comment]
This error was caused by the fact that my search regex phrase was not returning any results.
I updated the Title and keyword strings in the config, and all works as expected.

**Comment by ralyodio** [comment]
what did you change it to?
